version: '3'

services:
  backend:
    image: backend:1.0.0
    tty: true
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '30000:30000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    image: frontend:1.0.0
    tty: true
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '30001:30001'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:7.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: admin
    volumes:
      - 'phonecallDb:/data/db'
    ports:
      - '27017:27017'

volumes:
  phonecallDb:
