version: '3'

services:
  backend:
    tty: true
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    tty: true
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:7.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: admin
