apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
  labels:
    app: app-backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: backend
  selector:
    app: app-backend-service
