apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: backend
          image: backend:1.0.0
          ports:
            - containerPort: 3000
