apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: frontend
          image: frontend:1.0.0
          ports:
            - containerPort: 8080
