apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
  selector:
    app: backend
