apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:1.0.0
          ports:
            - containerPort: 30000
          env:
            - name: LOGIN
              valueFrom:
                secretKeyRef:
                  name: app-backend-secret
                  key: LOGIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-backend-secret
                  key: PASSWORD
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-backend-secret
                  key: TOKEN_SECRET
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: app-backend-secret
                  key: MONGO_URL
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
