apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001
  selector:
    app: frontend
