apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_INITDB_ROOT_USERNAME: 'root'
  MONGO_INITDB_ROOT_PASSWORD: 'example'
  MONGO_INITDB_DATABASE: 'admin'
  mongo.conf: |+
    storage:
      dbPath: /data/db
    security:
      authorization: enabled
    net:
      bindIp: 0.0.0.0
      port: 27017
